### ISSUE TITLE
long status text

### ISSUE THREAD

**Issue by Steve-Mcl** [Steve-Mcl/node-red-contrib-cron-plus#1]
use requested...
* check box to disable
* if possible, reduced "next run" 
reference: https://discourse.nodered.org/t/new-a-flexible-scheduler-node-incl-timezone-support-node-red-contrib-cron-plus/13686

**Comment by x821938** [comment]
What about an option for showing relative time? Eg:
Next Run: ~1d
Next Run: ~7h
Next Run: ~2m
Then you change the accuracy the closer you get to the trigger time.

**Comment by Steve-Mcl** [comment]
Somewhat shortened in V0.2.0 release.  Will re-open if necessary.
