### ISSUE TITLE
Simply doesn't work...

### ISSUE THREAD

**Issue by TroLoos** [Steve-Mcl/node-red-contrib-cron-plus#12]
Anyone else have a problem whit this node?

I've set up an extensive schedule for my 13 roller blinds, 2 schedulers for each (summer schedule, winter schedule). I wanted to disable half of them depending on weather conditions (stop-all / start-all command). I don't use dynamic schedules, just static definitions.

But they started to live their own lives... sometimes bursting events, sometimes silent as a grave...

For example: according to schedule an event should be triggered at 23:00, but even after 23:00 (verified a clock in docker, all fine) it still shows that next event is going to occur at 23:00. Oh, btw, my node red is inside a docker container but it shouldn't be an issue, all different schedulers work just according to time.

Something is seriously mixed up, I am on version 1.0.3. Did 1.0.4 that just arrived fix this? I didn't have a chance to test it.

**Comment by Steve-Mcl** [comment]
Hello,
I have been looking into this for another user & I have just (moments ago) published a fix.

I would be most grateful if you could please try once more with the latest version (v1.0.6) and let me know how you get on?

Thanks for taking the time to raise an issue & letting me know.

Cheers, Steve.

**Comment by TroLoos** [comment]
Hi Steve,

I've enabled my schedules based on cron-plus and at first look it already looks MUCH better.

All the next scheduled events show up right, those based on time and solar events as well.

I will be observing their operation and let you know.

Thanks a lot for your support and contribution!

**Comment by TroLoos** [comment]
Hi Steve, after short evaluation it seems a lot better, but still not perfect... take a look at example screenshot:

[https://ibb.co/Wxk1gpr](url)

Next scheduled event for this node should be Civil Dusk which is approx at 21:48. It shows different, that a next scheduled event will be at 7:00 in the morning. It's 14:38 right now and timed events work fine so the clock is right.

In the evening I will know if this event will be fired according to my schedule, what would mean that only preview under node is wrong and schedules work just fine.

Perhaps I am doing something out of ordinary in my flow? I have a set of cron-plus nodes for hot days schedule, and another set of cron-plus nodes for cold days schedule. Every day in the morning I am sending start-all command to half of them and stop-all command to the other half, this way my blinds work differently in hot and cold days.

**Comment by Steve-Mcl** [comment]
Hi. 


Could you export that node or tell me the location coordinates please?

Also, what is your timezone?

**Comment by TroLoos** [comment]
Hi, here's the exported node:

`[{"id":"ac5a01d3.fd238","type":"cronplus","z":"7a52768a.94b118","name":"[W] Lounge [R]","outputField":"cron_payload","timeZone":"","persistDynamic":false,"commandResponseMsgOutput":"output1","outputs":1,"options":[{"name":"open @ 7:00 [15%]","topic":"Open","payloadType":"num","payload":"15","expressionType":"cron","expression":"0 0 7 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"},{"name":"open @ 7:30 [100%]","topic":"Open","payloadType":"num","payload":"99","expressionType":"cron","expression":"0 30 7 * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"},{"name":"close @ civil dusk [0%]","topic":"Close","payloadType":"num","payload":"0","expressionType":"solar","expression":"0 * * * * * *","location":"51.95485 20.15837","offset":"1","solarType":"selected","solarEvents":"civilDusk"}],"x":220,"y":1060,"wires":[["dcea59b5.a70a38"]]}]`

My timezone is Europe/Warsaw, right now it is GMT +2 as far as I know. But it shouldn't be an issue, the nodes that do not fire sun events do not fire them at all, not on a wrong time.

Funny is that after changing this node, it reloads showing next event properly ;-)

**Comment by Steve-Mcl** [comment]
Hi - nice place Warsaw, was there a couple of years back (me and a bout 10 other guys travel from England to various parts of Poland every year for a "knees up" :) )

> Funny is that after changing this node, it reloads showing next event properly ;-)

I imported your export & as you say - it looks correct.

I wonder if it was just a status update / visual issue?

Can you do me a favour please - check that the 3 events occur at the correct time (attach a debug node to save you watching ;) ) and let me know if the node performs correctly please?

In the mean time, I will see if I can repeat your issue.

**Comment by TroLoos** [comment]
What I did right now was to refresh all my cron-plus nodes, by adding a new solar event and removing it.

For now it looks like all the next scheduled events are looking right.

Is it possible that after updating node version they need to be re-applied to schedule solar events properly?

**Comment by Steve-Mcl** [comment]
> Is it possible that after updating node version they need to be re-applied to schedule solar events properly?

shouldnt but there is always the possibility I am not handling the upgrade from one version to the next correctly.

sometimes I open + click Done on nodes "just in case"

Glad it is OK now.

I'll close this issue for now, but please re-open if necessary.
