### ISSUE TITLE
suggestion: confignode with credential for location

### ISSUE THREAD

**Issue by hklages** [Steve-Mcl/node-red-contrib-cron-plus#14]
Hi. I just installed the node and created several schedules for sunset, sunrise, civil dusk, civial dawn. 

First question: Is there any possibility to copy the location? 
Suggestion:  with an config node for location I would be easy to use that location in all nodes. 

Second Question: 
I use a button "night" being set true with "sunset" and false with "sunrise". 
If I restart the flow the button might have the wrong status.   
Any suggestion how to set the right value after flow restart? Can I use your node to only receive the values for sunrise, sunset at a given location?

**Comment by Steve-Mcl** [comment]
> First question: Is there any possibility to copy the location?

Do you mean copy a schedule entry to simplify entering location multiple times? That is something I might consider.
In the mean time, I'm sure you realise you can ctrl+c copy ctrl+v paste lat/lon text from the input box

> Suggestion: with an config node for location I would be easy to use that location in all nodes.

The original intent is that each schedule is independent of each other.
That said, I will put some thought into a "default location" that would be used if the location filed of a schedule is left blank - would that do? 
OR - do you mean you use separate CRON nodes and hope for a separate config node?

>I use a button "night" being set true with "sunset" and false with "sunrise". If I restart the flow the button might have the wrong status.

Would you help me look into this please?  If you can select on your editor the nodes involved & press CTRL+E to export then then reply to this message and paste in your flow between backticks...

` ``` `
` paste flow between backticks like this `
` ``` `

and provide a step by step of what you do and what you see - I will definitely look into it.

Many thanks for your feedback.

**Comment by hklages** [comment]
Default location would be great (that's very close to a config node).
I could not do copy and paste - maybe because of issue 15. 

**button**: I use a dashboard with a lot of "state" buttons (see picture). 
Example "Nacht" (English Night). It is set true (blue color) with cron plus, civil dusk and false with cron plus civil dawn. That works fine and I am able to use it as trigger for blinds, lights, etc.  This button is in sync with a global variable. 

If I (accidentially) stop the flow 5 minutes before civil dusk and restart it 5 minutes after the button "Nacht" shows the wrong or none value. Thats what I want to avoid. 
A solution would be a small "restart" flow, injecting the current time and validating whether it is later then civil dusk and before civil down and set the button. Thats does not seem to be possible with your node - right?

![Screenshot_20200709-080520_Edge](https://user-images.githubusercontent.com/17273119/87003723-75a54800-c1bc-11ea-8247-9d8d6735270f.jpg)

**Comment by Steve-Mcl** [comment]
> A solution would be a small "restart" flow, injecting the current time and validating whether it is later then civil dusk and before civil down and set the button. Thats does not seem to be possible with your node - right?

On this point, it is fully possible and actually one of the most vocal requests.

If you have an inject (set to trigger on start up) fire a topic of "status" and a payload with the schedule name, you will get a status where you can get current solar state.

example...
![image](https://user-images.githubusercontent.com/44235289/88368352-cc4a7e80-cd85-11ea-99d6-634080801b3f.png)

```
[{"id":"5021bf88.bc854","type":"cronplus","z":"8f35f92.a1dd908","name":"","outputField":"payload","timeZone":"","persistDynamic":false,"commandResponseMsgOutput":"output1","outputs":1,"options":[{"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"solar","expression":"0 * * * * * *","location":"64.26726145448768 -20.390625","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}],"x":860,"y":180,"wires":[["ccc0f945.0c6e88"]]},{"id":"fa5b2270.53c5d","type":"inject","z":"8f35f92.a1dd908","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"status","payload":"schedule1","payloadType":"str","x":850,"y":120,"wires":[["5021bf88.bc854"]]},{"id":"ccc0f945.0c6e88","type":"debug","z":"8f35f92.a1dd908","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload.result.status.nextDescription","statusType":"msg","x":1070,"y":140,"wires":[]}]
```

**Comment by hklages** [comment]
aah - great. Thanks.
