### ISSUE TITLE
location

### ISSUE THREAD

**Issue by hklages** [Steve-Mcl/node-red-contrib-cron-plus#15]
Hi. I use node-red 1.0.5, cron-plus 1.06, windows 10 edge browser. 
The location data is not in the field - can you change that? 

![cronplus](https://user-images.githubusercontent.com/17273119/86899616-8bf2cb80-c10a-11ea-8bd6-e8754dc567e3.png)

**Comment by Steve-Mcl** [comment]
Yeah, I spotted this yesterday when I upgraded node-red :(

Thanks for raising this as an issue for me - it is appreciated.

**Comment by Steve-Mcl** [comment]
This is (i believe) fixed in latest release V1.0.7 

I will close this but if your issue persists after updating and restarting/refreshing the browser, please re-open the issue.

Thanks, Steve.

**Comment by hklages** [comment]
yes - now it works fine. Thanks.
