### ISSUE TITLE
dynamic solar events not working correctly ..

### ISSUE THREAD

**Issue by MKoroschetz** [Steve-Mcl/node-red-contrib-cron-plus#18]
I have been using cron-plus for over a year in my home automation flows, without any issues. A couple of day ago I upgraded to v1.07 in order to take advantage of the new "solar events" features, which I typically inject dynamically through a function node.
Following the strange behavior I am getting and which I am unable to work around or find a solution for.
_Environment_: Node Red running on a raspberry 3 on Debian 9 (stretch).
I inject the following in a cron-plus node which has NO static entries (tested with static entries gives the same issues). Longitude, Latitude and TimeZone are taken from a global flow variable:

**UPDATE**: Turns out that after additional tests, the issue was passing "latitude" and "longitude" out of order. Once I corrected my mistake the result appears to be correct. The corrected line below must read:
````
Corrected: "location": s.lat + ', ' + s.long,
Mistaken:  "location": s.long + ', ' + s.lat,
````
From original post:
```
s = global.get('location);   
 msg.payload =   [
        {   "command": "remove-all" },
        {
            "command": "add",
            "topic": "switch01_dusk",
            "name": "switch01_dusk",
            "payloadType": "str",
            "payload": "1",
            "expressionType": "solar",
            "solarType": "selected",
            "solarEvents": "civilDusk",
            "location": s.long + ', ' + s.lat,
            "timeZone": s.TZ,
            "offset": 0
        },
        {
            "command": "add",
            "topic": "switch01_on",
            "name": "switch01_on",
            "expressionType": "cron",
            "expression": "0 08 20 * * * *",
            "payloadType": "str",
            "payload": "1",
            "timeZone": s.TZ,
        },        
       {
            "command": "add",
            "topic": "switch01_off",
            "name": "switch01_off",
            "expressionType": "cron",
            "expression": "0 08 23 * * * *",
            "payloadType": "str",
            "payload": "0",
            "timeZone": s.TZ,
        },
        {   "command": "status-all" }
    ];
```
cron expressions are taken correctly and do trigger as expected. However the solar event produces the following status output:
```
object
topic: "init"
payload: object
  command: object
  result: array[3]
  0: object
    config: object
    status: object
        type: "dynamic"
        modified: false
        isRunning: true
        count: 0
        limit: 0
        nextDescription: "civilDusk in 4 days 10 hours 48 minutes 11 seconds"
        nextDate: "2020-08-10T11:10:07.724Z"
        nextDateTZ: "Aug 10, 2020, 07:10:07 EDT"
        timeZone: "America/New_York"
        serverTime: "2020-08-06T00:21:56.105Z"
        serverTimeZone: "UTC"
        description: "Solar Events: 'civilDusk'"
        solarState: object
        solarTimes: array[1]
           0: object
           event: "civilDusk"
           time: "2020-08-10T11:10:07.724Z"
           timeOffset: "2020-08-10T11:10:07.724Z"
1: object
2: object
_msgid: "4beacb13.5e81e4"
```
The issue is that the next "civilDusk" event is set to 4 days in the future, when it obviously should be the next day. The actual time also seems a bit of when compared to other nodes providing the same event time at the same coordinates.

I get a similar result with other solar events I have tested.

Thank you for looking into this issue. Once this is resolved I believe your node is a very complete and simple way to automate any and all time based events in any automation scenario.

**Comment by Steve-Mcl** [comment]
Hi, so I've had no others mention this and it has been quite some time since I have heard from you so i will close the issue but feel free to re-open if necessary.
