### ISSUE TITLE
dynamic events do not show "payload" when previewed...

### ISSUE THREAD

**Issue by MKoroschetz** [Steve-Mcl/node-red-contrib-cron-plus#19]
In the attached picture you can see that the payload information is not shown on the schedule. It would obviously be convenient at least for completeness.
![image](https://user-images.githubusercontent.com/37051843/89478073-e9575800-d75c-11ea-863f-9369b3c67c4d.png)

For any listed solar event, it would also be nice to see the time for the next upcoming event.

**Comment by Steve-Mcl** [comment]
I think this is catered for the best I can muster right now in the new release of V2.0.0

![image](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/assets/44235289/20f7c116-c1b4-4413-a236-925b592d63ca)
