### ISSUE TITLE
Whilst editing flows, sometimes cronjobs linger

### ISSUE THREAD

**Issue by RedShift1** [Steve-Mcl/node-red-contrib-cron-plus#23]
When editing a flow and regularly deploying using the "Modified Flows" button, sometimes cron jobs with previous configurations that are no longer in the flow, still run.

The only way to get rid of the lingering cron jobs is to use the "Restart Flows" option.

Node-RED version: 1.1.3
cron-plus version: 1.2.1

**Comment by Steve-Mcl** [comment]
Hi @RedShift1 thanks for the feedback. I will try to recreate this and handle it.

To be honest, I rarely use modified flows or full deploy so have never witnessed this.  Until I contain this, perhaps you might consider using modified nodes method until I have nailed it down?

**Comment by RedShift1** [comment]
The flow I was working on is done so I won't touch it anymore for some time.

I've been looking through the source code and when the node closes (`this.on('close', ...)`), it checks whether or not the node is being removed and when it's not it tries to affect the minimum amount of change to what's already running. But perhaps it's best to just stop everything and re-use the node's initialization logic to start all tasks again.

**Comment by Steve-Mcl** [comment]
> The flow I was working on is done so I won't touch it anymore for some time.
Cool - so no major rush - phew :) 

thanks for the heads up - I will keep this issue open as a reminder (should get to it in about a week)

Cheers.

**Comment by Steve-Mcl** [comment]
@RedShift1  please update an test - i believe I have contained this in V1.3.0

**Comment by RedShift1** [comment]
Looks ok now - no problems
