### ISSUE TITLE
Likely documentation typo

### ISSUE THREAD

**Issue by tmichaeltx** [Steve-Mcl/node-red-contrib-cron-plus#27]
I have not verified that it is working correctly while being labelled incorrectly (though I expect it is). I see that in help tab for Cronplus and in the dropdown itself for "Selected Solar Events" Sunset is shown as (0.833°) when I believe it should be (-0.833°).

Based on the calculation window that appears when I select location, it is doing the calculation correctly, it is just the documentation of this 1 solar event that needs repair.

**Comment by Steve-Mcl** [comment]
thanks for the feedback.

**Comment by Steve-Mcl** [comment]
Note this is corrected in the repo & will be in the next release.
