### ISSUE TITLE
Feature: DateTime events added via payload do not exist after a restart.

### ISSUE THREAD

**Issue by jaswalters** [Steve-Mcl/node-red-contrib-cron-plus#29]
Would love to see events added via payload exist after a restart. If I have a few schedules set i will lose them if a restart occurs.

**Comment by Steve-Mcl** [comment]
Hi, I am sure the persist option saves and restores this type of dynamic schedule. Could you give it a go?

**Comment by jaswalters** [comment]
> Hi, I am sure the persist option saves and restores this type of dynamic schedule. Could you give it a go?
> 
> Ps, are you using latest version?

Thank you! I did not see that option. Worked like a champ!
