### ISSUE TITLE
Allow for setting payload to native JS types

### ISSUE THREAD

**Issue by dvv** [Steve-Mcl/node-red-contrib-cron-plus#3]
Due to by default truthy `permitDefaults` at https://github.com/Steve-Mcl/node-red-contrib-cron-plus/blob/master/cronplus.js#L359 `task.node_type` is forced at https://github.com/Steve-Mcl/node-red-contrib-cron-plus/blob/master/cronplus.js#L373 to not be `null`. This is turn forbids to branch to https://github.com/Steve-Mcl/node-red-contrib-cron-plus/blob/master/cronplus.js#L142.

Am I right this is a bug, or how do I dynamically add tasks with payload of, say, function or another non-JSON-serializable type.

TIA

**Comment by Steve-Mcl** [comment]
Hi, I am not 100% certain what you mean - are you attempting to have a JS function as a function?

If so, that is not the normal pattern for node-red however I understand why you might want to do that.

Normally, in this kind of scenario, you would set the payload or topic (to send in the output) to something you know - then when the output is sent, you use other nodes to run a function.

e,g, CRON (output topic: "calculateSomething") --> switch node (if msg.topic=="calculateSomething" then ouput1) --> function node (calculateSomething)

Does that make sense?

**Comment by dvv** [comment]
Hi!
This _does not allow_ for queueing arbitrary tasks _dynamically_, as one need _to hardcode_ a switch + function node.

**Comment by Steve-Mcl** [comment]
Hi, i believe this is now handled correctly.  Please install version from github and try. (not yet updated in NPM)

alternatively, reply with a small flow demonstrating the issue and I will test it.
