### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by drmibell** [Steve-Mcl/node-red-contrib-cron-plus#30]
I wonder whether `cron-plus` needs to log so many [info] messages to the console. Using the log to debug new nodes or flows, I have seen many (sometimes over 1000) messages from just a couple of instances of `cron-plus`. I sometimes end up filtering the log, which is an extra step, and then getting cranky because there is nothing there from my own work. Am I just being fussy?

**Comment by Steve-Mcl** [comment]
Hi could you provide a couple of small samples of the most frequent entries please?

When I was figuring out how to handle system time changes I added additional logging & may have left some logging in that I didn't mean to. 

Thanks for the feedback.

**Comment by drmibell** [comment]
I think this is fairly typical. There's more where it came from

8 Jan 22:45:17 - [info] [cronplus:c291fddf.102d48] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"* * * * Tue#3","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}
8 Jan 22:45:17 - [info] [cronplus:c291fddf.102d48] createTask - index: 1, static: true, opt: {"name":"front_door_off","topic":"schedule2","payloadType":"default","payload":"","expressionType":"solar","expression":"0 * * * * * *","location":"39.33854604847979 -78.75","offset":"0","solarType":"selected","solarEvents":"sunrise"}
8 Jan 22:45:17 - [info] Started flows
8 Jan 22:46:16 - [info] Stopping flows
8 Jan 22:46:16 - [info] Stopped flows
8 Jan 22:46:16 - [info] Starting flows
8 Jan 22:46:16 - [info] [cronplus:c291fddf.102d48] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"* * * * Tue#3","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}
8 Jan 22:46:16 - [info] [cronplus:c291fddf.102d48] createTask - index: 1, static: true, opt: {"name":"front_door_off","topic":"schedule2","payloadType":"default","payload":"","expressionType":"solar","expression":"0 * * * * * *","location":"39.33854604847979 -78.75","offset":"0","solarType":"selected","solarEvents":"sunrise"}
8 Jan 22:46:16 - [info] Started flows
8 Jan 23:38:44 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
8 Jan 23:38:45 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 00:18:27 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 00:18:27 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 00:27:35 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 00:27:35 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 12:58:44 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 12:58:44 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 12:58:44 - [info] [cronplus:c291fddf.102d48] createTask - index: 1, static: true, opt: {"name":"front_door_off","topic":"schedule2","payloadType":"default","payload":"payload","expressionType":"solar","expression":"0 * * * * * *","location":"39.33854604847979 -78.75","offset":"0","solarType":"selected","solarEvents":"sunrise","type":"date"}
9 Jan 15:19:12 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 15:19:12 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 15:48:02 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 15:48:02 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 16:45:22 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 16:45:22 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 17:06:28 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
9 Jan 17:06:28 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
9 Jan 18:36:48 - [info] Stopping flows
9 Jan 18:36:48 - [info] Stopped flows
9 Jan 18:36:48 - [info] Starting flows
9 Jan 18:36:48 - [info] [cronplus:c291fddf.102d48] createTask - index: 0, static: true, opt: {"name":"schedule1","topic":"schedule1","payloadType":"default","payload":"","expressionType":"cron","expression":"* * * * Tue#3","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}
9 Jan 18:36:48 - [info] [cronplus:c291fddf.102d48] createTask - index: 1, static: true, opt: {"name":"front_door_off","topic":"schedule2","payloadType":"default","payload":"","expressionType":"solar","expression":"0 * * * * * *","location":"39.33854604847979 -78.75","offset":"0","solarType":"selected","solarEvents":"sunrise"}

**Comment by Steve-Mcl** [comment]
Hi Michael,

The "createTask" entries will  be kept as it proves evidence schedules were created (for debugging purposes)

However, the "System Time Change Detected" and "Refreshing running schedules" should rarely be seen - this is somewhat of a concern.

If you have a look at the cronplus code I added to detect system time changes (and thus always trigger schedules at the correct time) you will see if checks the system clock every 1sec & if a 5sec time difference is witnessed since the last 1sec check - it refreshes the schedules. 

Looking at your log, there is one of 3 things I suspect is happening...
1. The code clock check is buggy (possible but not so likely, it is very simple and doesnt happen on my systems)
2. your clock is drifting lots (possible but not that likely)
3. you are running code in node-red that hogs the processor / event loop for extended periods of time & nodejs fails to update its copy of system time (more likely)

Is this instance of node-red performing some rather large / lengthy blocking operations?

It would be interesting to understand your issue before I propose and changes.

**Comment by drmibell** [comment]
This is more interesting than I expected. Going back through the logs, those are the only two types of message I find. I'll check my flow for possible cpu hogs, though I don't see anything that **should** be a problem. This may take a while, since the messages seem to appear only every few hours. 

I should have said that this is happening on my laptop (macintosh), so it could be related to other processes or the version of node.js or how it was installed. I'll let you know what I find.

**Comment by Steve-Mcl** [comment]
@drmibell do these log entries coincide with your laptop going to sleep?

**Comment by drmibell** [comment]
Good question. I'll play with the sleep interval, force it to sleep, etc. and see what happens.

**Comment by drmibell** [comment]
> do these log entries coincide with your laptop going to sleep?

I should have taken a second to actually answer your question -- YES, I think so.

The most recent console log:
n 13:14:44 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
11 Jan 13:14:44 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules
11 Jan 13:15:58 - [info] [cronplus:c291fddf.102d48] System Time Change Detected!
11 Jan 13:15:59 - [info] [cronplus:c291fddf.102d48] Refreshing running schedules

The mac's powermanagement log:
13:14:44.032302 -0500	powerd	
13:14:44.269290 -0500	powerd	[System: PrevIdle]
13:14:44.335615 -0500	powerd	[System: PrevIdle]
13:14:48.028288 -0500	powerd	DarkWake from Normal Sleep [CDN] due to EC.LowBattery/LowBattery:
13:14:48.029476 -0500	powerd	hibmode=3 standbydelay=10800
13:14:48.029887 -0500	powerd	WakeTime: 5.269 sec
13:14:48.032707 -0500	powerd	
13:14:48.046407 -0500	powerd	Entering Sleep state due to 'Low Power Sleep':
13:15:07.048802 -0500	powerd	[System: PrevIdle]
13:15:15.146963 -0500	powerd	[System: PrevIdle DeclUser kDisp]
13:15:16.051872 -0500  	powerd	
13:15:58.401377 -0500	powerd	
13:15:58.443263 -0500	powerd	[System: PrevIdle DeclUser kDisp]
13:15:58.463576 -0500	powerd	[System: DeclUser kDisp]
13:15:58.473387 -0500	powerd	[System: DeclUser kDisp]
13:15:58.492957 -0500	powerd	[System: DeclUser kDisp]
13:15:58.779235 -0500	powerd	[System: PrevIdle DeclUser kDisp]
13:15:59.086414 -0500	powerd	[System: PrevIdle DeclUser kDisp]
13:16:00.983269 -0500	powerd	[System: DeclUser kDisp]
13:16:00.984756 -0500	powerd	DarkWake from Hibernate [CDN] due to EC.ACAttach XHC1/UserActivity Assertion:
13:16:00.985561 -0500	powerd	hibmode=3 standbydelay=10800
13:16:00.986034 -0500	powerd	WakeTime: 8.904 sec
13:16:00.989646 -0500	powerd	
13:16:01.030538 -0500	powerd	Kernel Idle sleep preventers: IODisplayWrangler
13:16:01.032962 -0500	powerd	Display is turned on
13:16:01.067799 -0500	powerd	Warning level: 1 time: -1 cap: 131
13:16:03.691469 -0500	powerd	DarkWake to FullWake from Hibernate [CDNVA] due to UserActivity Assertion:
13:16:03.692312 -0500	powerd	hibmode=3 standbydelay=10800
13:16:03.692529 -0500	powerd	WakeTime: 2.687 sec
13:16:03.697372 -0500	powerd	

This is complicated by the machine going into hibernate rather than normal sleep and having a low battery condition, but I think you've spotted the issue.

**Comment by Steve-Mcl** [comment]
Thanks for checking. 

The problem now how to handle this (or not)

The event loop is being stopped & thus the code detects an outage. 

It's a doozy.  

If I drop the logging, people might have issues the don't know about. Then again, it's not this nodes responsibility to catch this. Hmmmmm. I'll have a think. Feel free to comment with ideas 🤔

**Comment by drmibell** [comment]
Two questions before I go off to think. Will this issue affect any system that goes to sleep? What exactly is the node looking for, or what does it mean when it says a system time change has been detected?

**Comment by Steve-Mcl** [comment]
The code is very simple. See for you self [here](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/blob/9b02a4c25e9d638bbea82989fcd1812e8848cda1/cronplus.js#L760)

In node, there is no means of detecting a time change other than monitoring it yourself. Also (afaik), there is no way to detect computer sleep or hibernate.  And since it's a single thread event loop it is hard to tell the difference. 

There is no real harm and yes, any system that sleeps will see this entry but typically, systems running node-red with a Cron schedule typically don't sleep. 

In case you are wondering why this code is even in the node, it's been seen that standard inject and other schedule nodes can "run out" when system time changes. This is especially problematic for the likes of the raspberry pi which doesn't have an RTC & relies on NTP that can occur after node-red starts.

**Comment by Steve-Mcl** [comment]
I think we can close this one now?

**Comment by drmibell** [comment]
I suppose so. It's clear why you want to monitor the clock and refresh the tasks but not so obvious why everything needs to be logged. 

On the plus side, I've been reminded again that my MacBook still has some quirks running Node-RED. Despite its resemblance to systemd, I can't get launchd to restart NR reliably at reboot, and when I start NR manually it fails to find some settings, including the current project. Since launchd is what actually handles cron-like tasks, there may be a connection here. I'll keep looking.
