### ISSUE TITLE
Slight suggestion about terms used.

### ISSUE THREAD

**Issue by Just-another-pleb** [Steve-Mcl/node-red-contrib-cron-plus#32]
This had me confused for a while.

The fields of entry are:
second
minute
hour
day of month
month
day of week
year

But "day of month"
I don't know but usually that is the date - isn't it?
DAY - to me - implies:  Monday, Tuesday, Wednesday etc.
Where as DATE is a number from 1 - 31 (depending on the month.)

Just a thought.

**Comment by Steve-Mcl** [comment]
Hi the terms used are fairly consistent across all Cron implementations. Besides, the built in help and dynamic info tip fully explain the values. It is almost impossible to get it wrong. 

Don't misunderstand, I appreciate what you are saying but to remain consistent across Cron implementations this won't change.

**Comment by Just-another-pleb** [comment]
No problems.

Just I guess I am not used to that term "Day of the month" but more "Date".
