### ISSUE TITLE
No output for `list-all-dynamic`?

### ISSUE THREAD

**Issue by hepcat72** [Steve-Mcl/node-red-contrib-cron-plus#33]
Hi again @Steve-Mcl,

It's entirely possible that I am misunderstanding how the "Ability to control via simple topic commands" (as described in the [README](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/blob/master/README.md)) is supposed to work.  Here's what I expect to happen.  Let me know if I've got it right: If I connect an injection node with the topic set to (for example) `list-all-dynamic`, the `Command responses only` output should spit out the information about entries in the dynamic schedule.  However, either I'm incorrect about that, or there appears to be a bug?  I tried with and without a setting for the payload in the injection.

I made a screen recording to demonstrate what I tried.  Did I do something wrong or am I misunderstanding how it's intended to work?  I updated to the latest version (from 1.4.0 to 1.4.2) and restarted node-red to try this before submitting this issue.

Here is what I see:

https://drive.google.com/open?id=1ifA3nP7oKxjfwuN8fer40pwGvzEMJIe5

**Comment by Steve-Mcl** [comment]
Hi, it looks like i missed something.  Try `status-all-dynamic` (list-xxx is exactly the same as `status-xxx` so the output is the same)

I'll fix it up on the next update.

thanks.
