### ISSUE TITLE
Feature: remove-stopped and show-active

### ISSUE THREAD

**Issue by hepcat72** [Steve-Mcl/node-red-contrib-cron-plus#36]
I've been using cronplus to schedule HDHomeRun recordings with VLC using TVPI files downloaded from TitanTV.com, and as I've been using it, I noticed that my expired dynamic schedule list has grown and grown.  I hadn't scheduled any for the past week's time and was able to clear out my list of 34 "All stopped" items using the `delete-all-dynamic` command.  I hadn't been able to do this in the past because I always had a few that were yet to fire off, and doing them individually was too cumbersome, so I was wondering if you could add a feature to remove only those items that will never fire off again.

I noted that you already have code to determine if all the items are "stopped" since the node status "All stopped" seems to imply that case:

<img width="199" alt="Screen Shot 2021-03-31 at 9 07 AM" src="https://user-images.githubusercontent.com/2300532/113150067-acffcd00-9201-11eb-96cf-f19a0c411498.png">

Similarly, it would be nice that if I wanted to view upcoming scheduled items, I could filter out those that are "stopped".

So I would like to request some version of the following commands:

- show-active-dynamic
- show-stopped-dynamic
- remove-stopped-dynamic

While I'm at it, it's notable that the doc for the node refers in an example to "delete-all-dynamic", but "delete" isn't listed as one of the commands.  I assume it's an alias for "remove" and that you at some point changed "delete" to "remove".  Assuming "remove" works (I only tried "delete"), you might consider updating the doc to reflect consistent command terminology.

**Comment by Steve-Mcl** [comment]
Hi, some good points raised.  Let me see what I can do.

Regarding the "remove" and "delete" - they are simply aliases (I forget now which came first but rather than remove it, it was safer to leave it in (not really using any processor cycles & provided backwards compatibility)

**Comment by Steve-Mcl** [comment]
Hi @hepcat72 

I have published (to github only) V1.5.0

This is the release notes...

* Added new filtering to commands `-active`, `-active-dynamic`, `-active-static`, `-inactive`, `-inactive-dynamic`, and `-inactive-static` support for commands remove, export and status (e.g. you can now remove all dynamic schedules that have finished with the command `remove-inactive-dynamic`)
* Status no longer shows "All Stopped" if there isn't actually any schedules
  * This is more accurate than "All Stopped" and makes the current state clearer
* Update built in help and readme
* Updated the big demo

Hopefully these are self explanatory and hopefully the updated built-in help is ok? 

If you are willing, I would greatly appreciate it if you could install, test and feedback. Let me know so I can publish to NPM.

<br>

To install this version, please use npm to install from the githb repo...

```bash
cd ~/.node-red
npm install Steve-Mcl/node-red-contrib-cron-plus
```

... where `~/.node-red` is the folder of your installation (often `c:/users/username/.node-red` on windows)

Cheers, Steve.

**Comment by hepcat72** [comment]
Great! Just started Easter vacation today. I'll update when I get back.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Steve-Mcl** [comment]
Hi @hepcat72 - did you have a chance to test this? 

It would be great if you could feedback soon so I can release updates.

Thanks you.

**Comment by hepcat72** [comment]
Will certainly do. Still catching up from vacation, and I replaced my Wireless AP. My schedule was empty since vacation, but I have added a few that fired off over the past few days. (Incidentally, my wife discovered that she really likes the 80s movie "Earth Girls are Easy".)  So I'll update, add another current recording, and attempt to clear out the expired ones.

**Comment by hepcat72** [comment]
OK.  I tried it out over lunch, but appear to have either done something wrong - or there's an issue.  I created screenshots.  Hopefully they paint a complete picture.  Let me know if I did anything incorrectly.

![install-restart](https://user-images.githubusercontent.com/2300532/114754405-8c1d9880-9d26-11eb-8bd1-ef5979f51e7f.png)
![dynamic-sched2](https://user-images.githubusercontent.com/2300532/114754406-8cb62f00-9d26-11eb-8bc8-f8f334555967.png)
![injection-success](https://user-images.githubusercontent.com/2300532/114754407-8cb62f00-9d26-11eb-9ca6-ef0c5ccaa9c3.png)
![palette](https://user-images.githubusercontent.com/2300532/114754408-8cb62f00-9d26-11eb-9307-be4952c0285a.png)
![inject-settings](https://user-images.githubusercontent.com/2300532/114754411-8cb62f00-9d26-11eb-824b-d750aaa24e6b.png)
![dynamic-sched1](https://user-images.githubusercontent.com/2300532/114754412-8d4ec580-9d26-11eb-9ea0-72f03e3ffa12.png)
![cronplus-settings](https://user-images.githubusercontent.com/2300532/114754413-8d4ec580-9d26-11eb-8d45-02ad10585054.png)
![flow](https://user-images.githubusercontent.com/2300532/114754415-8d4ec580-9d26-11eb-912c-68a1030f61ff.png)

**Comment by hepcat72** [comment]
Note that the date/time is embedded in the Name in the dynamic schedule data. The last 3 scheduled items are in the future.  The 6 at the top are all old.

**Comment by hepcat72** [comment]
Very Minor Aside: When looking at the dynamic schedule, I'm aware that my filenames have the channel and datetime twice, which is a new dumb mistake somewhere, but even before I made that mistake, the cron expression column is always squeezed and vertical (if not scrolled off the right side), and probably a vertical scrollbar on the right side would be useful for when you have more than a handful dynamic items.

**Comment by Steve-Mcl** [comment]
Hi, i have found (i think) the issue and will publish to the repo in just a moment. 

I have also tweaked the layout of the dynamic display (it really does need a makeover - its on my list but has very little priority) 

NOTE scroll bars should appear where required. and the dynamic schedules dialog is resizable.

**Comment by Steve-Mcl** [comment]
now published as v1.5.1

Please test & hopefully working as expected 🤞

Thanks for your support.

**Comment by hepcat72** [comment]
I'll give it a go, next chance.  NP

**Comment by hepcat72** [comment]
OK. `1.5.1` worked as expected.  Thanks a ton!  I will use this often.

Observations: I had kind of expected output from the node (connected to debug) saying how many were removed or remained. Since there wasn't, I viewed the dynamic schedule.  Initially, it showed all previous entries, but refreshed itself within a second to show the 3 entries I'd expected. The refreshed dialog was partially off the top of the window, but clicking the refresh button re-centered it.  Although, depending on the pre-remove dynamic schedule size and previous scroll position, I could envision the updated dialog being completely off the top of the window (if the final list is small enough), even though the page is scrolled to the top.  I'm sure that it can be recovered somehow.  It just could be briefly confusing if that happens to someone.

**Comment by Steve-Mcl** [comment]
Glad it works. Phew. 

> I had kind of expected output from the node (connected to debug) saying how many were removed or remained

I have thought about this but unsure what the payload would look like. Would it include removed count? Removed items names?  Remaining count? 

I initially left it as was because it is easy enough to query the node.

Any thoughts?

**Comment by hepcat72** [comment]
I don't care that much, TBH - as long as it works.  My opinion would be to output to that status output, but only if that's consistent with the responses you've created for other commands already.  I cannot envision a use-case where anyone may want to do something when N events are removed, but who knows (maybe they have other things to clean up?).  I usually err on the side of always giving the user extra outputs/triggers.  Alternatively, since I can't think of a concrete use-case, a temporary node status change seems appropriate, (whether or not there's an output spit out).
