### ISSUE TITLE
cron 0 15,30,45 -> 0 trigger

### ISSUE THREAD

**Issue by bruma59** [Steve-Mcl/node-red-contrib-cron-plus#39]
Is it possible that only 15, 30 and 45 min have a trigger and not at the hour (0)?

**Comment by Steve-Mcl** [comment]
`0 15,30,45 * * * * *` should work

![image](https://user-images.githubusercontent.com/44235289/119251834-a6a62580-bba0-11eb-82ff-34260536d8e4.png)


As should `0 15/15 * * * * *`
![image](https://user-images.githubusercontent.com/44235289/119251892-eec54800-bba0-11eb-915a-06e1ff35c973.png)
