### ISSUE TITLE
SyntaxError: Unexpected token p in JSON at position 0

### ISSUE THREAD

**Issue by IoTPlay** [Steve-Mcl/node-red-contrib-cron-plus#4]
Hi, looks like just what I need, but cannot get it to work. I pass the following into this node:

`
[{"command":"add",    
"name":"shellyem-B9F209/emeter/1",    
"type":"json",    
"expression":"0 */1 * * * *"}]    
`

When the node triggers (every minute), it produces the following error:

`SyntaxError: Unexpected token p in JSON at position 0`.

What am I dong wrong?

**Comment by IoTPlay** [comment]
When I removed `"type":"json"` the message was sent.

**Comment by Steve-Mcl** [comment]
Hi, its had to tell from what you have written here but i recently resolved a problem when setting a dynamic cron entry & the payload was an object. see #4
