### ISSUE TITLE
v1.5.3 Triggering Restart

### ISSUE THREAD

**Issue by rgerrans** [Steve-Mcl/node-red-contrib-cron-plus#41]
Since updating yesterday, many of my scheduled events appear to be causing Node- Red to restart when they trigger. Seems to be correlated to sun events.

**Comment by Steve-Mcl** [comment]
Could you capture the log output of node red - it will have vital clues.  Thanks.

**Comment by Steve-Mcl** [comment]
I think I have found the issue and I've posted a new version (V1.5.4)

Please test and let me know.

Sorry for the inconvenience. 

Steve.

**Comment by rgerrans** [comment]
That fixed it, thanks.
