### ISSUE TITLE
[FR] - Query for the node status / next event string?

### ISSUE THREAD

**Issue by LumiGeek** [Steve-Mcl/node-red-contrib-cron-plus#43]
Hi there,

Cron-plus is fantastically useful and works perfectly, thanks so much.  Had a quick feature request (unless there is already a way to do this that I am missing)-

Is there, or can you add, a payload or topic command that returns the Node Status string showing the upcoming next event?  Would be great to be able to display it in a text box of my dashboard, instead of just visible in the flow editor.

Thanks so much,
joejoe

**Comment by Steve-Mcl** [comment]
Thanks for the compliments. 

You have a couple of options...

1. Use a status node (however it only fires when status text changes) 
2. Send a message with topic set to "status" and the payload set to the name of the schedule. 

You can also send a message with topic "status-active" and grab the result with the lowest nextDate value

Have a read through the built in help and try out the built in examples (CTRL+I)

**Comment by LumiGeek** [comment]
Status node works perfectly for my application.  And thanks for teaching me
something new despite it not being directly related to your node :)

Cheers,
jj

**Comment by Karine005** [comment]
Hello, how can I retrieve the next topic or payload when several crons are actives ?
Thank you.

**Comment by Steve-Mcl** [comment]
You can send status-all topic and get back a list of schedules that you can interrogate.

**Comment by Karine005** [comment]
Ok, but how interrogate the list to obtain the next topic ?
