### ISSUE TITLE
90 second timer

### ISSUE THREAD

**Issue by ger19wmu** [Steve-Mcl/node-red-contrib-cron-plus#45]
So this is perhaps me just not using the node properly....but I am trying to trigger a message every 90 seconds in the month of December.  When I tried to set it for every 1.5 minutes the node reported an invalid expression so i switched to 90 seconds.  Now it says I have a good expression and that it will send at 90 seconds, but it still sends at 60 seconds....even in the expression builder it shows it will send at 60 seconds in the example times:
![cron](https://user-images.githubusercontent.com/74634110/145858277-b255f049-6013-46c2-bc0f-5c833444f268.png)

I can confirm that even as shown, it does send a packet every 60 seconds rather than 90....is this a potential bug or am I just configureing this totally wrong!?  Thanks for the help!

**Comment by Steve-Mcl** [comment]
Hi @ger19wmu 

This is a limitation of cron.

What you can do instead is two 3min timers 1.5mins apart...


![image](https://user-images.githubusercontent.com/44235289/145861894-c31d0527-fe8d-41d4-8cab-fb81446675a3.png)

![image](https://user-images.githubusercontent.com/44235289/145861908-0661fd33-be3b-46b1-bbb5-1b283790d60c.png)

then you get a `msg` every 90 secs.

**Comment by ger19wmu** [comment]
That works!!  Thanks for the quick reply and help solving the problem!!! Much appreciated!
