### ISSUE TITLE
Wrong time in status text (24:30)

### ISSUE THREAD

**Issue by A380Coding** [Steve-Mcl/node-red-contrib-cron-plus#46]
Below the cronplus node (status text) I get a strange time for the following cron setting "0 30 0 * * *"
It reads: 24:30 GMT+1
It should be 00:30 GMT +1

It is only the indicated time in the status text. It works fine and triggers at the right moment.

**Comment by Steve-Mcl** [comment]
That is odd indeed. 

Any chance you could paste a screen shot snippet into a reply and also tell me what versions of node, node-red & Cron-plus you are using? 

Also, what timezone is set on your node-red box?

Cheers.

**Comment by A380Coding** [comment]
![cron](https://user-images.githubusercontent.com/80172816/146455358-126387f6-72c7-422c-9592-06183f9a3f8b.jpg)

Sure. Screenshot attached. NR 2.1.3 as docker container. CronPlus 1.5.4

Timezone is Europe/Berlin

**Comment by Steve-Mcl** [comment]
Hmmmmm

On a server set for Europe/London (timezone left blank on cronplus)...
![image](https://user-images.githubusercontent.com/44235289/146524199-1ea4072d-78c9-4d01-a4e4-e70e3c32f468.png)

On a (windows) server set for /EuropeLondon & cronplus timezone set to Europe/London...
![image](https://user-images.githubusercontent.com/44235289/146524697-c68f1017-fd81-4450-b0c0-e51afc165cb3.png)

Setting the timezone (of cronplus - not the server) to "Europe/Berlin" ...
![image](https://user-images.githubusercontent.com/44235289/146524453-c5ed01b0-7420-4291-b892-e4a0ce4f8bd0.png)

I will test setting a windows and linux OS timezone to Europe/Berlin later (on a sacrificial server)

In the mean time, could you 
* double check the timezone set on the container (not the host OS)?
* tell me the nodejs version running inside the container?
* tell me which docker image you are using?
* export a sample flow with this issue?

Cheers, Steve

**Comment by A380Coding** [comment]
Timezone in cronplus is empty. Timezone in Dockercontainer is set to the one mentioned (checked) using TZ variable.
Dockercontainer in use: nodered/node-red

I have to create a sample flow later. How can I check nodejs version ?

**Comment by Steve-Mcl** [comment]
If you can access a terminal in the container, enter `node -v` 

If you can't access the containers terminal, try the same command via an exec node in node-red. 

Also, while you are in the terminal of the container, what does `date` report?

**Comment by A380Coding** [comment]
NodeJ: V14.18.1
Date:  Fri Dec 17 20:12:01 CET 2021

**Comment by A380Coding** [comment]
And the sample flow:

`[
    {
        "id": "dfc351a6628c5e01",
        "type": "tab",
        "label": "test",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "ddabd56417a61870",
        "type": "cronplus",
        "z": "dfc351a6628c5e01",
        "name": "",
        "outputField": "payload",
        "timeZone": "",
        "persistDynamic": false,
        "commandResponseMsgOutput": "output1",
        "outputs": 1,
        "options": [
            {
                "name": "schedule1",
                "topic": "schedule1",
                "payloadType": "default",
                "payload": "",
                "expressionType": "cron",
                "expression": "0 30 0 * * *",
                "location": "",
                "offset": "0",
                "solarType": "all",
                "solarEvents": "sunrise,sunset"
            }
        ],
        "x": 600,
        "y": 280,
        "wires": [
            []
        ]
    }
]`

**Comment by Steve-Mcl** [comment]
@A380Coding I got the chance to debug this issue this morning. I believe the issue is resolved. Please update via npm or palette. 

Cheers for your feedback.

**Comment by A380Coding** [comment]
Ok, cool. I will check on it later.

**Comment by A380Coding** [comment]
Working fine. Issue solved. Thanks!
