### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by Paul-Reed** [Steve-Mcl/node-red-contrib-cron-plus#48]
It would be great if we could better control the logging to the node-RED log.
Currently, even with log level set to `info`, Cron+ consumes the log, especially at startup where I get pages of Cron+ data making it difficult to spot any abnormal system messages. I guess that's because I use Cron+ so much!
Even during normal running, Cron+ prints any triggers in the log, again which are not really needed and I would expect to find in `debug` if I had a problem. 

Could it be possible to enable/disable logging via a tickbox in the config page, or increasing the level at which the messages are printed to the log, such as `debug`

First reported https://discourse.nodered.org/t/cron-excessive-logging-at-startup/57024 and which contains screenshots from Julian (TotallyInformation) and myself.

**Comment by juggledad** [comment]
This is still an issue I'd also like to see changed to an option

**Comment by Steve-Mcl** [comment]
A level of curation has been undertaken in v2.0.0 - released today. Most debug logs are now **debug** logs (i.e. only shown when nodered debug level is set to debug)

Please feel free to suggest further enhancements if this is still too noisy on the default log level.

Thanks for the feedback.

And apologies for the delay (work+home life be damned :) )
