### ISSUE TITLE
Is there a way to use this node to add entries to a system or user crontab?

### ISSUE THREAD

**Issue by hepcat72** [Steve-Mcl/node-red-contrib-cron-plus#51]
Love this node.

I have one annoying problem though... I have a "DVR" workflow where this node outputs dynamic schedule messages to exec nodes that record TV shows. I have 1 pair of shows that record on Sunday morning (Face the nation and Meet the Press). But I often mess around in node red on Sunday mornings and have learned that re-deploying kills those recording processes running in the exec nodes.

To avoid that, I thought maybe this node could be used to append to the user's or the system crontab?  Has anyone done that with the command response output? Or is there a way to set the cronplus node to "use" a user's crontab as it's basis for events (like supply the command to it and everything)?

**Comment by Steve-Mcl** [comment]
Hi @hepcat72 

Unfortunately, this is (like most nodes) a pure js implementation of crontab & does not interface with the OS.  This permits it to work truly cross platform.


> But I often mess around in node red on Sunday mornings and have learned that re-deploying kills those recording processes running in the exec nodes

Do you mean processes launched by node-red are stopped/killed when deploying changes? Are you doing full, partial or node deploy?  A node deploy should not stop your processes.
