### ISSUE TITLE
Adjustable MAX_CLOCK_DIFF

### ISSUE THREAD

**Issue by grunkyb** [Steve-Mcl/node-red-contrib-cron-plus#53]
This feature request relates to the discussion in #30 about sources of log entries reading "System Time Change Detected!" and refreshing schedules.

Processes I'm running overnight on a Pi 3B+ take up enough CPU time that they cause multiple instances where the system time drifts enough that differences are greater than 5000 ms set by `MAX_CLOCK_DIFF`. This happens even with the overnight processes being run at high nice values. The result is processes starting that were previously stopped.

Please could you add a feature that would allow me to tailor this value from within NR (rather than manually editing a line)? Or please could you suggest a workaround?

**Comment by Steve-Mcl** [comment]
in v2, the env var `CRONPLUS_MAX_CLOCK_DIFF` can be set to a higher ms value.  Default is 5000.
