### ISSUE TITLE
Typo at documentation

### ISSUE THREAD

**Issue by burner-** [Steve-Mcl/node-red-contrib-cron-plus#56]
![image](https://user-images.githubusercontent.com/3836115/184947023-ef72fac2-9fff-4fd7-8c0c-dca774dbf453.png)
Document say that there is -inactive-all-dynamic suffix for commands. But it is -inactive-dynamic.

**Comment by Steve-Mcl** [comment]
Thanks, I have corrected this. Will publish an update soon

**Comment by Steve-Mcl** [comment]
Eventually published v2.0.0
