### ISSUE TITLE
incorrect solarState

### ISSUE THREAD

**Issue by Nazarbayevv** [Steve-Mcl/node-red-contrib-cron-plus#58]
Hello.

I used node an a few year without any issueds. But I updated my system yesterday + DST ended this night and I can see solarState isuue now.
Node send me "Night" solarState at 15:15 by local time

{"triggerTimestamp":1667135710013,"status":{"type":"static","modified":false,"isRunning":true,"count":0,"limit":0,"nextDescription":"nightEnd in 13 hours 42 minutes 48 seconds","nextDate":"2022-10-31T02:57:58.278Z","nextDateTZ":"31 Oct 2022, 04:57:58 EET","timeZone":"Europe/Kiev","serverTime":"2022-10-30T13:15:10.021Z","serverTimeZone":"Europe/Kiev","description":"All Solar Events","solarState":{"state":"Night","direction":"rise","day":false,"night":true,"astrologicalTwilight":false,"nauticalTwilight":false,"civilTwilight":false,"goldenHour":false,"twilight":false,"morningTwilight":false,"eveningTwilight":false,"dawn":false,"dusk":false,"morningGoldenHour":false,"eveningGoldenHour":false},"solarTimes":[{"event":"nightEnd","time":"2022-10-31T02:57:58.278Z","timeOffset":"2022-10-31T02:57:58.278Z"},{"event":"nauticalDawn","time":"2022-10-31T03:35:44.792Z","timeOffset":"2022-10-31T03:35:44.792Z"},{"event":"civilDawn","time":"2022-10-31T04:14:09.646Z","timeOffset":"2022-10-31T04:14:09.646Z"},{"event":"sunrise","time":"2022-10-31T04:48:17.102Z","timeOffset":"2022-10-31T04:48:17.102Z"},{"event":"sunriseEnd","time":"2022-10-31T04:51:53.029Z","timeOffset":"2022-10-31T04:51:53.029Z"},{"event":"morningGoldenHourEnd","time":"2022-10-31T05:36:01.509Z","timeOffset":"2022-10-31T05:36:01.509Z"},{"event":"solarNoon","time":"2022-10-31T09:43:31.819Z","timeOffset":"2022-10-31T09:43:31.819Z"},{"event":"eveningGoldenHourStart","time":"2022-10-31T13:51:02.129Z","timeOffset":"2022-10-31T13:51:02.129Z"},{"event":"sunsetStart","time":"2022-10-31T14:35:10.610Z","timeOffset":"2022-10-31T14:35:10.610Z"},{"event":"sunset","time":"2022-10-31T14:38:46.537Z","timeOffset":"2022-10-31T14:38:46.537Z"},{"event":"civilDusk","time":"2022-10-31T15:12:53.993Z","timeOffset":"2022-10-31T15:12:53.993Z"},{"event":"nauticalDusk","time":"2022-10-31T15:51:18.847Z","timeOffset":"2022-10-31T15:51:18.847Z"},{"event":"nightStart","time":"2022-10-31T16:29:05.361Z","timeOffset":"2022-10-31T16:29:05.361Z"},{"event":"nadir","time":"2022-10-31T21:43:31.819Z","timeOffset":"2022-10-31T21:43:31.819Z"}],"solarEvent":"nightEnd"},"config":{"topic":"topic1","name":"schedule1","payloadType":"default","payload":"","limit":null,"expressionType":"solar","solarType":"all","solarEvents":"sunrise,sunset","location":"50.40791541307151 30.33092057705744","offset":"0"}}

**Comment by Nazarbayevv** [comment]
Hm, but node-red-contrib-cron-plus works correctly today.

**Comment by Steve-Mcl** [comment]
Hi, sorry I missed your comment. Please reopen this if you can make this problem repeatable and I'll take a look. 

Thanks for reporting otherwise.
