### ISSUE TITLE
Please use properly name-spaced CSS classes and element ids

### ISSUE THREAD

**Issue by knolleary** [Steve-Mcl/node-red-contrib-cron-plus#6]
This node introduces a lot of CSS styles for very generically named classes and elements. This means it is highly likely to clash with other nodes and elements and cause rendering issues.

For example: `form-tip`, `#map` etc.

Nodes should use properly namespaced CSS and element IDs to ensure they don't cause unintended clashes.

For example, instead of giving an element an id of `map`, it ought to be `cron-plus-map`.

And `form-tip` should be `cron-plus-form-tip`.

**Comment by Steve-Mcl** [comment]
fixed in 6a35f82 (v0.6.7)
