### ISSUE TITLE
Suggestion: A button to expand the schedule list

### ISSUE THREAD

**Issue by Just-another-pleb** [Steve-Mcl/node-red-contrib-cron-plus#60]
A button to expand the schedule view to full screen

**Comment by Steve-Mcl** [comment]
hi, which part? the dynamic schedules view? the list of schedules? the whole node edit panel?

**Comment by Just-another-pleb** [comment]
(26 March was a long time ago.)
I think in/on the EDIT screen.

Only that if you have a few entries it is crowded.
Similar to the `function` node when open it allows full screen editing.

![Screenshot from 2023-07-24 14-51-23](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/assets/39888280/0bd34566-6a14-458b-b707-7b60b6f59bef)

So in cronplus this part expands to full screen.

![Screenshot from 2023-07-24 14-49-42](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/assets/39888280/ef1a35b6-89c2-4233-8618-1c60dbc1306f)

**Comment by Steve-Mcl** [comment]
> (26 March was a long time ago.)

Yeah - damned home life, work etc getting in the way of play time - my apologies.

**Comment by Steve-Mcl** [comment]
ok, I now understand your request. I will have a look see if it is possible using existing node-red mechanisms or via simple HTML/JS.

NOTE:  If I have to duplicate functionality, I dont think you will get your (perfectly reasonable) wish. ;)

**Comment by Just-another-pleb** [comment]
Wouldn't it be done with the same *mechanics* of how the `function` node does it?
(just saying)

Anyway, hope it is possible and not too hard.

**Comment by Just-another-pleb** [comment]
That looks good.  :)

**Comment by Steve-Mcl** [comment]
I kept the fullscreen and added a CSS way to expand to full window instead of full screen.

Fullscreen can still be used by holding "shift" when you click the expand button.

Will release soon.
