### ISSUE TITLE
ERR_REQUIRE_ESM after upgrade on Node Red 3.0.2

### ISSUE THREAD

**Issue by davies8172** [Steve-Mcl/node-red-contrib-cron-plus#63]
![image](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/assets/61297305/fc244b4f-da6c-42f2-861f-25eef18e3cba)
After upgrade from 1.5.0, it will not run in Node-Red and shows error "ERR_REQUIRE_ESM" in the palette menu.
Have tried a complete uninstall and reinstall but same error appears.

**Comment by jostrasser** [comment]
Hi,

same here:

![image](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/assets/14274103/5479758d-abc6-4fbe-95ed-3f6278244ca8)

**Comment by FrontFelix** [comment]
got the same issue.

**Comment by Steve-Mcl** [comment]
Thanks guys, fix incoming.

Last minute dependency update dropped CJS for commonjs and broke it :(

**Comment by Steve-Mcl** [comment]
2.0.1 published and updated on flows library. It may take up to 30 minutes to be populated in the node-red catalog.

Sorry for the troubles.

**Comment by jostrasser** [comment]
Thanks for the quick response and fix! :)
