### ISSUE TITLE
Not an issue, but a question.

### ISSUE THREAD

**Issue by MikeEcho0815** [Steve-Mcl/node-red-contrib-cron-plus#69]
How to fire the cron-plus event on nodeRed startup? As known "inject once after startup" from the default node.

**Comment by Steve-Mcl** [comment]
It is something I could never find a "great" way of supporting. It never felt like a useful thing for me as it can be achieved by a separate inject. 

But if you really want to trigger a schedule on start up, I did add support by passing a msg in (from an inject, set to trigger on start). Set the topic to "trigger" and payload to "name-of-schedule"

**Comment by Steve-Mcl** [comment]
Or topic of "trigger-all" (I think I added support for that- check the built in help)

**Comment by MikeEcho0815** [comment]
I can work with that, thank you for replying. I just thought I missed something in the UI. Of course I can just plug a standard inject node in front of yours. Great plug in by the way. 👍🏼
