### ISSUE TITLE
Make cronjob persistent

### ISSUE THREAD

**Issue by ArduChecker** [Steve-Mcl/node-red-contrib-cron-plus#8]
Hi Steve, I am sure that is not the right entry point to bring that subject forward...but I'll found your work very interesting on how to arrange cron jobs via node red...I did something similar without a dedicated node, I mixed something together found there in the internet which allows me to define a cron string via a web page and then pushing that string to a machine via MQTT payload which is retreived by a python script which scheduled finally the job.
As node red server and the machine where the jobs is established are separated there is no need to persistent cron job related data...however, when you with your code...question is: Is there a possibility to persistent the jobs so that they will survice a restart (server / node-red)? Kind regards, Michael

**Comment by Steve-Mcl** [comment]
Hi, I am considering persistence however this is totally possible already.

Store your dynamic entries in a file and one node-red start, use a startup inject to add them back in.

**Comment by Steve-Mcl** [comment]
Hi. V1.0.0 in GitHub now has persistence capabilities. 

Would you be kind enough to test the new features?

**Comment by Steve-Mcl** [comment]
Version 1.0.2 in npm and on flows library now has persistence.
