### ISSUE TITLE
Requests to set dynamic schedules aren't accepted, but still parsed correctly?

### ISSUE THREAD

**Issue by torbjorn-stabo** [Steve-Mcl/node-red-contrib-cron-plus#81]
Using node-red-contrib-cron-plus v2.1.0, Node-RED v18.0.4 in Home assistant.

This is the flow configuration:
![bild](https://github.com/user-attachments/assets/3226a207-c3ef-4c30-9ca5-20be7ddcbdc0)

This is the input to the cronplus node. The expected result is that two dynamic schedule items are created and set to run. 
![bild](https://github.com/user-attachments/assets/e41a2178-f574-4974-8297-05bc9e8ef76e)

This is the result;
![bild](https://github.com/user-attachments/assets/cd4a32ef-063c-4881-9851-652cf02a591d)
It seems that the input is parsed correctly, since the description field contains the correct data. But still the 3rd column for the folded schedule is null (Not 'Never' which I would've expected if there was a problem with the expression input field. Why null? Some bug in the cronplus node?) It's the same for both pre and post schedules, the 3rd column is null. ..and as can be seen in the flow configuration image above, the cronplus node says 'All stopped'.

**Comment by Steve-Mcl** [comment]
Hi, usually i dont answer questions here, rather on the Node-RED forum.  However, I tested what you had and it works fine here!

![chrome_9dO7wo6PHX](https://github.com/user-attachments/assets/e1372ea7-9e1e-482c-b4df-6d3efcff2a87)

```
msg.payload = [
    {
        command: "add",
        name: "next gbg coll - pre",
        expression: "0 10 20 28 AUG * 2024",
        expressionType: "cron",
        payloadType: "default",
        limit: 1
    },
    {
        command: "add",
        name: "next gbg coll - post",
        expression: "0 0 1 26 AUG * 2024",
        expressionType: "cron",
        payloadType: "default",
        limit: 1
    }
]
return msg;
```


---

PS, in future, please post code as text not screenshots (screenshots are had to read and I have to re-type everything manually!).  Ta.

**Comment by Steve-Mcl** [comment]
I realise this is from 1 month ago (as I said before I typically dont answer questions on the issue tracker but rather on the forum) so you may well have solved this already. 

So I will close this for now - however please do reply is there is still an issue.
