### ISSUE TITLE
why does it take over a day to execute?

### ISSUE THREAD

**Issue by juansolanop** [Steve-Mcl/node-red-contrib-cron-plus#82]
I have the following payload schedule sent at 5am

{
  "expression":"0 6 * * 0,1,2,3,4,5",
  "name":"test",
  "payload": "test",
  "command":"add"
}

Why the next date occur until 1 day and 1 hour instead of 1 hour?

How do I fix this?

**Comment by Steve-Mcl** [comment]
Paste a screenshot of node edit page with the tooltip visible.

Also, tell me the timezone you are in and the timezone set on the computer where node-red is installed.

**Comment by juansolanop** [comment]
Here is what you requested, all timezones are set to EDT

![Screenshot 2024-08-24 at 9 03 02 PM](https://github.com/user-attachments/assets/2040d776-481b-4ab1-937c-d9454ca7c62e)
![Screenshot 2024-08-24 at 8 57 57 PM](https://github.com/user-attachments/assets/010e8273-d79c-4cc2-993c-3812883566e1)
![Screenshot 2024-08-24 at 8 57 34 PM](https://github.com/user-attachments/assets/8c01e0f7-3ead-4251-9562-15b4012a8c76)
![Screenshot 2024-08-24 at 8 57 09 PM](https://github.com/user-attachments/assets/abd880ef-30f3-4c3d-bc7a-68f30de617c8)

**Comment by Steve-Mcl** [comment]
Regardless of the dynamic status, does the node actually trigger when you expect?

Can you try again and show me a screenshot of the node AFTER injecting the payload (I want to see the status underneath it). 

Also include what time you inject and current time in the screenshot and the Cron you use for this.

**Comment by juansolanop** [comment]
Hi @Steve-Mcl  I think I found the issue, I started counting the days of the week on Monday = 0 instead of Sunday =0, this off-shifted the last value of my crontab expression causing the odd behavior

Today is Sunday so, fixing the value at the end to 7 I cannot longer reproduce the issue:

{
  "expression":"0 6 * * 7",
  "name":"test",
  "payload": "test",
  "command":"add"
}

Thanks for the help, I will close the issue now
