### ISSUE TITLE
2nd output for eg status

### ISSUE THREAD

**Issue by remygiraud** [Steve-Mcl/node-red-contrib-cron-plus#9]
Thanks for providing this. I am using it extensively!!
In the readme:
`Option to separate control responses from output 1 to seperate 2nd output`

However, from my experience, when I send a "status" command to the node, it uses the only output available and therefore it triggers the rest of the flow, unless I add a switch node to control what is the content of the output.
Am I missing something or would it be an improvement to add a second output to check that all "command" sent to the node are processed? Eg. start could output the cron data...

**Comment by Steve-Mcl** [comment]
Hi, I have just uploaded V1.0.0.beta that has this very feature.

If you would be kind enough to test, you can install this beta by running

`npm install Steve-Mcl/node-red-contrib-cron-plus`
